### ISSUE TITLE
$dirofhex-id:AB CD EF 00$ doesn't seem to work

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-NG#4]
$dirofhex-id:AB CD EF 00$ just return a single number 0-3 for me..
does this function work for anyone else?

i think i used 
$dirofhex-id:{$hex-idofname:Stone Gargoyle$}$#string<>#XXX XX X
to hunt Stone Gargoyle's in  in Tibiafun.eu back in 2012 (very strong creature that i had to lure to a specific spot then move to an other specific spot in order to kill, and only as long as nobody else was hunting it), but now the code seems to  just read a Byte somewhere..  
How is this function supposed to work?
Is it working now?
Did it ever work?

**Comment by blackdtools** [comment]
It used to extract the current looking direction of a creature, based on info contained in some packets. A Tibia creature can only look in 4 directions.
- Daniel

**Comment by divinity76** [comment]
oh ok, sorry for the confusion
